resources:
  - name: git
    type: git
    source:
      uri: git@github.com:MERN-Stack-Dev-Group-graphQL/neighborly-server.git
      branch: dev
      private_key: ((private_key))

jobs:
  - name: deploy-to-server
    serial: true
    plan:
      - get: git
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: alpine
          inputs:
            - name: git
          outputs:
            - name: server
              path: git
          params:
            NEIGHBORLY_ENV: ((neighborly_env))
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd git &&
                npm i &&
                echo "$NEIGHBORLY_ENV" >> .env

          
            
